export const data = {
  email: "",
  password: "",
  rePassword: "",
  firstName: "",
  lastName: "",
  phone: "",
  language: 0,
  birthDate: "",
  idNumber: "",
  country: "",
  city: "",
  street: "",
  zipCode: "",
  moreDetails: "",
  certificateNumber: "",
  isAgree: false,
  creditCardNumber: "",
  creditCardExpire: "",
  CVC: "",
};

export const fakeData = {
  email: "moti2003@gmail.com",
  password: "moti2003",
  rePassword: "moti2003",
  firstName: "Moti",
  lastName: "Elmakies",
  phone: "0586552717",
  language: 0,
  idNumber: "036383289",
  country: "Israel",
  city: "Ramat Gan",
  street: "Shderot Yerozhalaim",
  zipCode: "510021",
  companyName: "Temp Company",
  moreDetails: "some more detailsss",
  certificateNumber: "",

  isAgree: true,
  creditCardNumber: "058023212321321",
  creditCardExpire: "0224",
  CVC: "351",
};
